### ISSUE TITLE
Referencing constructor params is not handled

### ISSUE THREAD

**Issue by mad-gooze** [timocov/ts-transformer-minify-privates#13]
Hi! Thanks for a nice lib!

I am trying to use it in my project, and I've found an issue with constructor params.

Please see a unit test in https://github.com/timocov/ts-transformer-minify-privates/pull/12

It is broken now - https://github.com/mad-gooze/ts-transformer-minify-privates/blob/reference-ctor-params-unit-test/tests/test-cases/reference-ctor-params/input.ts#L5 (`privateField ` is not replaced so resulting code is incorrect)

**Comment by timocov** [comment]
Hey,

I appreciate your feedback!

Looks like a bug. Would you like to make fixes for this issue as well?

**Comment by mad-gooze** [comment]
I'll try to work out a fix this week.

**Comment by schmidt-sebastian** [comment]
@mad-gooze I work on the Firebase SDKs (https://github.com/firebase/firebase-js-sdk) and am trying to evaluate whether we can use this library as a starting ground for minification. Unfortunately, this issue is a major blocker for us. 

At first glance, the fix does not seem to be super straightforward, as your test case illustrates:

```console.log(privateField);```

`console`, `log` and `privateField` are all simply marked as Identifiers and therefore indistinguishable. As such, we likely have to keep a mapping of the identifiers that we already  renamed within the current scope. I played around with this a little, and while it is certainly not rocket science, it does introduce state keeping to `ts-transformer-minify-privates`, which would be nice to avoid.

I don't want to duplicate our efforts and would like to know if you have already started looking into this and could use help? A fix for this issue would likely also allow us to rename any function argument, even outside of constructors.

**Comment by timocov** [comment]
Hey @schmidt-sebastian, thank you for reaching out.

> Unfortunately, this issue is a major blocker for us.

@mad-gooze could you please tell whether you've started on the fix for this issue or I could fix it instead?

> At first glance, the fix does not seem to be super straightforward, as your test case illustrates

Just for reference https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAYwDYEMDOa4GFUbgbwFgAoOMuMAVwCMkBLBRCAOzRikoRmgAoTyBFKHQBuKGMCGjxwAGJ1gSACYAuOM0oBbasCj9yASgL7BTVhCTAAdEggBzHmGFiJ8xUqvcAMhAQokBgDcJCaCaMAwACp0msAQlDA8PEYAvAB8ZmgW1rYOTtKuCsoGQaEAviQVxEA.

Actually here we can use type checker from the program to detect if one of the symbol's declaration is ctor parameter with `private` keyword and if so - just rename that identifier.

**Comment by timocov** [comment]
@mad-gooze ping

**Comment by mad-gooze** [comment]
sorry guys, fix is ready https://github.com/timocov/ts-transformer-minify-privates/pull/14

**Comment by timocov** [comment]
@mad-gooze thank you a lot for your work on this! All PRs are just merged into master. Give me some time and I'll release the new version (I'll comment here about it).

/cc @schmidt-sebastian

**Comment by timocov** [comment]
Looks like for now we can remove some unnecessary code (which is covered by new check), see https://github.com/timocov/ts-transformer-minify-privates/commit/f31764504fb270546f0551f566b1fd696d57b538 🎉

**Comment by timocov** [comment]
[Version 0.3.0](https://github.com/timocov/ts-transformer-minify-privates/tree/v0.3.0) has been released just now. npmjs - https://www.npmjs.com/package/ts-transformer-minify-privates/v/0.3.0.
