### ISSUE TITLE
private function referenced in an anonymous function

### ISSUE THREAD

**Issue by shiweiwei97** [timocov/ts-transformer-minify-privates#16]
Hi,

I found a case where the private function references are not handled which could cause runtime errors. Some code snippet.

```
private functionA {}

private functionB {
     document.getElementById("button").addEventListener("click", function(){
           this.functionA(); // not transformed
    }.bind(this));
}
```

The pattern is use .bind(this) for an anonymous function and call the private function within the anonymous function.
Workaround is to use arrow function or convert it to named function as another private members.

Thanks,
Weiwei

**Comment by timocov** [comment]
Hi,

do you have `strictBindCallApply` compiler option enabled? Also it might be "fixed" (as workaround) via adding `this: ClassName` as the first argument of function:

```typescript
class ClassName {
	private functionA {}

	private functionB {
	     document.getElementById("button").addEventListener("click", function(this: ClassName){
	           this.functionA(); // not transformed
	    }.bind(this));
	}
}
```

**Comment by timocov** [comment]
Looks like your example even can't be compiled due an error `'this' implicitly has type 'any' because it does not have a type annotation.(2683)` https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=9&pc=2#code/MYGwhgzhAEDC5QHJgLYFNoG8BQBIADgE4CWAbmAC4YBmArgHbAXED29AggBQCUWAvtjxEylGgyat6AIR5Y80BQoAmLYLXT0KAOgDmaCgFEQaDRSkBPAJJLOAIgBGtChTa3uAQi1glSg6TSaADLEEFT0aIR2oMTAANa2ADTQdIzMbDw4uIrZ2RQAFiFaKRJsXNwA3NAA9FXQ9CwU0BSEYPQQ1CyE6Eryinxa9sT0Nvkh3BV4AnxAA

But if you add `this: ClassName` it compiled successfully and I guess the name will be transformed as well https://www.typescriptlang.org/play/?strictBindCallApply=false#code/MYGwhgzhAEDC5QHJgLYFNoG8BQBIADgE4CWAbmAC4YBmArgHbAXED29AggBQCUWAvtjxEylGgyat6AIR5Y80BQoAmLYLXT0KAOgDmaCgFEQaDRSkBPAJJLOAIgBGtChTa3uAQi1glSg6TSaADLEEFT0aIR2oMTAANa2ADTQdIzMbJwUABYhAFxwCBDI6Nw4uIrl5VkhWikSbFzcANzQAPQt0PQsFNAUhGD0ENQshOhK8op8WvbE9DZVENxNeAJ8QA.

**Comment by shiweiwei97** [comment]
Thanks @timocov. `strictBindCallApply` is enabled. I find my repo doesn't enable `"noImplicitThis": true` in tsconfig.json. That is why my example passed compilation previously. With it enabled all the similar occurrences will be caught in compile time.

**Comment by timocov** [comment]
So it works now?

**Comment by shiweiwei97** [comment]
Yes, it works for me by enabling `noImplicitThis` so that it can detect the offending patterns during compile time. I think it is worth mentioning in the doc to recommend enable `noImplicitThis` in tsconfig.json.

**Comment by timocov** [comment]
PRs are welcomed :)
