### ISSUE TITLE
Error: "Cannot minify accessing for ..."

### ISSUE THREAD

**Issue by JohnWeisz** [timocov/ts-transformer-minify-privates#8]
Hey, thanks for this project, looks very useful.

I'm getting the error specified in the title of this issue for _some_ members, it's originating from [this line](https://github.com/timocov/ts-transformer-minify-privates/blob/master/src/properties-minifier.ts#L134):

```ts
if (!ts.isStringLiteral(node.argumentExpression)) {
    // it's access for private class' member - maybe need to warn here?
    throw new Error(`Cannot minify accessing for ${node.argumentExpression.getText()} property`);
}
```

Most other members minify fine, so it would be great if it was possible to ignore this error, instead of failing the build.

**Comment by timocov** [comment]
Hi!

> Most other members minify fine, so it would be great if it was possible to ignore this error, instead of failing the build.

Actually I've faced with that problem in case of accessing to property like this: `this._privateProp[this._privateProp2]` and just ignoring will get you `this._newName['_newName']` (there is no `this` in `[]`).

I would say that this project isn't ready for production yet, at least because there is no any tests and we cannot guarantee anything.

This project was something like a POC for my talk on the local meetup, and, unfortunately, I didn't spend enough time for it yet. But it shown great results (for example, reducing size for 5-6% for minified code and 2% for min.gz) and I going to revisit it, add tests at first and then fix bugs I faced in several projects currently I'm working on (they have a great codebase to test on them).

**Comment by timocov** [comment]
Hey @JohnWeisz, it looks like it should work for now.

Please check https://www.npmjs.com/package/ts-transformer-minify-privates/v/0.1.0 and tell how it is.

There was a change of name generation - for now the transformer doesn't minify properties, just renames with `_private_originalName`, so you can use terser/uglify with `mangle` option to minify them.

**Comment by timocov** [comment]
I'm going to close the issue because there is no more such errors in the package. If you'll have any other error - feel free to fill the issue.

**Comment by JohnWeisz** [comment]
Sorry about the lack of communication from my end, couldn't get to testing the new stuff earlier.
